/* Dad Bod — Admin gym program (satvikofficial20@gmail.com) + generic 3-day split */
(function () {
  "use strict";

  const EXERCISE_GIF_MAP = {
    "incline dumbbell press": "https://media.tenor.com/gxDKFjIkO9kAAAAC/incline-dumbells-press.gif",
    "incline dumbbell": "https://media.tenor.com/gxDKFjIkO9kAAAAC/incline-dumbells-press.gif",
    "barbell bench press": "https://media.tenor.com/mXQJeQyJCi4AAAAC/bench-press-regular-bench-press.gif",
    "bench press": "https://media.tenor.com/mXQJeQyJCi4AAAAC/bench-press-regular-bench-press.gif",
    "flat barbell bench": "https://media.tenor.com/mXQJeQyJCi4AAAAC/bench-press-regular-bench-press.gif",
    "cable cross": "https://media.tenor.com/p-__t8FMTtoAAAAC/cable-chest-fly.gif",
    "cable crossover": "https://media.tenor.com/p-__t8FMTtoAAAAC/cable-chest-fly.gif",
    "tricep overhead": "https://media.tenor.com/TC6IqRAa9csAAAAC/dumbell-overhead-tricep-extension.gif",
    "overhead cable extension": "https://media.tenor.com/TC6IqRAa9csAAAAC/dumbell-overhead-tricep-extension.gif",
    "tricep pushdown": "https://media.tenor.com/g0EulFQO22wAAAAC/rope-push-down.gif",
    "rope pushdown": "https://media.tenor.com/g0EulFQO22wAAAAC/rope-push-down.gif",
    "lat pulldown": "https://media.tenor.com/hI6Koi1EXhcAAAAC/close-grip-pull-down.gif",
    "pull down": "https://media.tenor.com/hI6Koi1EXhcAAAAC/close-grip-pull-down.gif",
    "t-bar row": "https://media.tenor.com/DPfMJrsdpTAAAAAC/t-bar-row.gif",
    "t bar row": "https://media.tenor.com/DPfMJrsdpTAAAAAC/t-bar-row.gif",
    "cable row": "https://media.tenor.com/R069mkP-46sAAAAC/cable-row-back.gif",
    "seated cable row": "https://media.tenor.com/R069mkP-46sAAAAC/cable-row-back.gif",
    "single-arm cable row": "https://media.tenor.com/R069mkP-46sAAAAC/cable-row-back.gif",
    "bicep curl": "https://media.tenor.com/j6wkDQurcm8AAAAC/incline-biceps-curl.gif",
    "incline dumbbell bicep": "https://media.tenor.com/j6wkDQurcm8AAAAC/incline-biceps-curl.gif",
    "preacher curl": "https://media.tenor.com/As5RbeZ43bEAAAAC/seated-biceps-curl.gif",
    "bayesian cable curl": "https://media.tenor.com/GYDvpl2ycIYAAAAC/cable-bicesp-curl.gif",
    "hammer curl": "https://media.tenor.com/rkexMgK5nn8AAAAC/reverse-cable-arm-curl.gif",
    "squat": "https://media.tenor.com/Pfj8vy41k-0AAAAC/gym.gif",
    "back squat": "https://media.tenor.com/Pfj8vy41k-0AAAAC/gym.gif",
    "hack squat": "https://media.tenor.com/Pfj8vy41k-0AAAAC/gym.gif",
    "romanian deadlift": "https://media.tenor.com/p4HVLW9g12sAAAAC/rdl.gif",
    "rdl": "https://media.tenor.com/p4HVLW9g12sAAAAC/rdl.gif",
    "leg extension": "https://media.tenor.com/jdljbWy_mdAAAAAC/leg-extension.gif",
    "calf raise": "https://media.tenor.com/zJk03-z7WI4AAAAC/calf-raise-workout.gif",
    "seated calf": "https://media.tenor.com/zJk03-z7WI4AAAAC/calf-raise-workout.gif",
    "leg raise": "https://media.tenor.com/LuTjJGyFOoUAAAAC/hanging-leg-raise.gif",
    "hanging leg": "https://media.tenor.com/LuTjJGyFOoUAAAAC/hanging-leg-raise.gif",
    "shoulder press": "https://media.tenor.com/X36vuP-nuVkAAAAC/dumbell-shoulder-press.gif",
    "dumbbell shoulder press": "https://media.tenor.com/X36vuP-nuVkAAAAC/dumbell-shoulder-press.gif",
    "lateral raise": "https://media.tenor.com/sxbft6ZWeK8AAAAC/cable-lateral-raise-single-arm.gif",
    "face pull": "https://media.tenor.com/FGsBtkQCchwAAAAC/face-pull.gif",
    "shrug": "https://media.tenor.com/uMNZPBaaTPYAAAAC/dumbbell-shrug.gif",
    "deadlift": "https://i.giphy.com/media/Uhzbmt0HWzeYYwQyX0/giphy.gif",
    "conventional deadlift": "https://i.giphy.com/media/Uhzbmt0HWzeYYwQyX0/giphy.gif",
    "leg press": "https://media.tenor.com/e0qeS17dv7QAAAAC/legpress45-leg-press.gif",
    "leg curl": "https://media.tenor.com/GLaVvK15troAAAAC/seated-leg-curl.gif",
    "lying leg curl": "https://media.tenor.com/GLaVvK15troAAAAC/seated-leg-curl.gif",
    "cable crunch": "https://media.tenor.com/Ja2_H5v54PQAAAAC/rope-crunch.gif",
    "kneeling cable crunch": "https://media.tenor.com/Ja2_H5v54PQAAAAC/rope-crunch.gif",
  };

  const SCIENCE_RULES = [
    'Train to 1–2 RIR: "Reps in Reserve." Your last 1 or 2 repetitions of every single set must feel incredibly difficult, near total failure.',
    "Control the Eccentric: Spend 2 to 3 seconds lowering the weight. The lowering phase causes the most muscle damage and subsequent growth.",
    "Track Everything: Write down your weights. If you benched 60 kg for 8 reps this Monday, you must attempt 60 kg for 9 reps or 62.5 kg for 8 reps next Monday.",
    "Prioritize Recovery: Complete physiological rest on rest days. Muscle growth happens during rest, not during the workout.",
  ];

  const ADMIN_GYM_SPLIT = [
    {
      day: 1,
      title: "Chest & Triceps",
      label: "Day 1 – Chest & Triceps",
      note: "Push day — upper chest emphasis and triceps finishers.",
      isOff: false,
      exercises: [
        {
          name: "Incline Dumbbell Press",
          sets: "3 x 8-10",
          cues: "Drive elbows down and in. Full stretch at bottom, controlled lockout.",
          science: "Provides a greater range of motion and better upper-chest fiber activation than a barbell.",
          timerSec: 90,
          trackWeight: true,
        },
        {
          name: "Flat Barbell Bench Press",
          sets: "3 x 6-8",
          cues: "Scapula retracted, feet planted, bar to mid-chest with control.",
          science: "The ultimate compound lift for overloading the sternal head of the chest.",
          timerSec: 120,
          trackWeight: true,
        },
        {
          name: "Cable Cross-overs (High-to-Low)",
          sets: "3 x 12-15",
          cues: "Soft elbows, squeeze chest at center. Constant tension throughout.",
          science: "Keeps constant tension on the chest, unlike dumbbells which lose tension at the top.",
          timerSec: 75,
          trackWeight: true,
        },
        {
          name: "Tricep Overhead Cable Extensions",
          sets: "3 x 10-12",
          cues: "Elbows fixed overhead, full stretch behind head, lock out at top.",
          science: "Trains the triceps long head in its fully stretched position, yielding superior hypertrophy.",
          timerSec: 90,
          trackWeight: true,
        },
        {
          name: "Tricep Rope Pushdowns",
          sets: "3 x 12-15",
          cues: "Elbows pinned to sides, split rope at bottom for peak contraction.",
          science: "Maximizes the peak contraction and isolates the lateral head.",
          timerSec: 75,
          trackWeight: true,
        },
      ],
    },
    {
      day: 2,
      title: "Pull (Back & Biceps)",
      label: "Day 2 – Pull (Back & Biceps)",
      note: "Thick back focus with complete biceps coverage.",
      isOff: false,
      exercises: [
        {
          name: "Lat Pulldowns (Medium Neutral Grip)",
          sets: "3 x 8-10",
          cues: "Pull elbows to ribs, chest high, squeeze lats at bottom.",
          science: "Studies show a shoulder-width neutral grip optimizes lat pull leverage and biomechanics.",
          timerSec: 105,
          trackWeight: true,
        },
        {
          name: "Chest-Supported T-Bar Row",
          sets: "3 x 6-8",
          cues: "Drive elbows behind body, hold squeeze 1 sec, no lower-back swing.",
          science: "Eliminates lower back limitations so you can fully isolate and overload the mid-back.",
          timerSec: 120,
          trackWeight: true,
        },
        {
          name: "Single-Arm Cable Row",
          sets: "3 x 10-12",
          cues: "Pull to hip, neutral spine, full stretch and contraction each rep.",
          science: "Allows you to pull in alignment with lat muscle fibers for a complete contraction.",
          timerSec: 90,
          trackWeight: true,
        },
        {
          name: "Incline Dumbbell Bicep Curls",
          sets: "3 x 8-10",
          cues: "Arms hang behind torso, stretch at bottom, no swinging.",
          science: "Places the biceps long head under extreme stretch, triggering rapid growth.",
          timerSec: 75,
          trackWeight: true,
        },
        {
          name: "Standing Hammer Curls",
          sets: "3 x 10-12",
          cues: "Neutral grip, elbows fixed, controlled tempo both directions.",
          science: "Targets the brachialis muscle, lifting the bicep up to create a thicker arm appearance.",
          timerSec: 75,
          trackWeight: true,
        },
      ],
    },
    {
      day: 3,
      title: "Legs & Abs",
      label: "Day 3 – Legs & Abs",
      note: "Quad-dominant compounds plus hamstring isolation and core finisher.",
      isOff: false,
      exercises: [
        {
          name: "Barbell Back Squats (or Hack Squats)",
          sets: "4 x 6-8",
          cues: "Brace core, depth with neutral spine, drive through mid-foot.",
          science: "The king of lower-body quad recruitment and systemic hormone response.",
          timerSec: 150,
          trackWeight: true,
        },
        {
          name: "Romanian Deadlifts (RDLs)",
          sets: "3 x 8-10",
          cues: "Hip hinge, soft knees, slow eccentric, feel hamstring stretch.",
          science: "Unbeatable for eccentric loading and stretching the hamstrings and glutes.",
          timerSec: 120,
          trackWeight: true,
        },
        {
          name: "Leg Extensions",
          sets: "3 x 12-15",
          cues: "Pause at top contraction, control the negative 2–3 seconds.",
          science: "Isolates the rectus femoris muscle, which squats cannot fully target.",
          timerSec: 75,
          trackWeight: true,
        },
        {
          name: "Seated Calf Raises",
          sets: "4 x 15",
          cues: "Full stretch at bottom, hold peak squeeze 1 sec at top.",
          science: "Targets the soleus calf muscle, which requires high repetitions to stimulate.",
          timerSec: 60,
          trackWeight: true,
        },
        {
          name: "Hanging Leg Raises",
          sets: "3 x 12-15",
          cues: "Posterior pelvic tilt, no swinging, control legs up and down.",
          science: "Studies confirm posterior pelvic tilt movements maximize lower rectus abdominis activation.",
          timerSec: 60,
          trackWeight: true,
        },
      ],
    },
    {
      day: 4,
      title: "Shoulders & Upper Back",
      label: "Day 4 – Shoulders & Upper Back",
      note: "Complete delt coverage and upper trap overload.",
      isOff: false,
      exercises: [
        {
          name: "Seated Dumbbell Shoulder Press",
          sets: "3 x 8-10",
          cues: "Brace core, press straight up, no excessive lower-back arch.",
          science: "EMG scans show dumbbell pressing activates the anterior deltoid more than a barbell.",
          timerSec: 105,
          trackWeight: true,
        },
        {
          name: "Cable Lateral Raises",
          sets: "4 x 12-15",
          cues: "Raise to shoulder height, slight forward lean, constant cable tension.",
          science: "Cables provide uniform resistance throughout the movement, unlike dumbbells which are easy at the bottom.",
          timerSec: 60,
          trackWeight: true,
        },
        {
          name: "Face Pulls (with external rotation)",
          sets: "3 x 15",
          cues: "Pull to face, elbows high, external rotate at finish.",
          science: "Hits the rear delts and rotator cuffs to fix posture and build shoulder width.",
          timerSec: 60,
          trackWeight: true,
        },
        {
          name: "Dumbbell Shrugs",
          sets: "3 x 10-12",
          cues: "Straight up-and-down shrug, no rolling, hold peak 1 sec.",
          science: "Overloads the upper trapezius muscle fibers.",
          timerSec: 75,
          trackWeight: true,
        },
      ],
    },
    {
      day: 5,
      title: "Pull (Back & Biceps)",
      label: "Day 5 – Pull (Back & Biceps)",
      note: "Posterior chain thickness and biceps peak work.",
      isOff: false,
      exercises: [
        {
          name: "Barbell Conventional Deadlifts",
          sets: "3 x 5",
          cues: "Neutral spine, bar close to shins, drive floor away, lock hips at top.",
          science: "Maximum central nervous system stimulation and full posterior chain thickness.",
          timerSec: 180,
          trackWeight: true,
        },
        {
          name: "Close-Grip Lat Pulldowns",
          sets: "3 x 10-12",
          cues: "Lean slightly back, pull to upper chest, squeeze lower lats.",
          science: "Increases the range of motion for lower lat recruitment.",
          timerSec: 90,
          trackWeight: true,
        },
        {
          name: "Dumbbell Preacher Curls",
          sets: "3 x 10-12",
          cues: "Armpits on pad, no momentum, full extension at bottom.",
          science: "Prevents momentum and isolates the short head of the bicep for a better peak.",
          timerSec: 75,
          trackWeight: true,
        },
        {
          name: "Bayesian Cable Curls",
          sets: "3 x 12",
          cues: "Face away from cable, arm behind torso, constant tension curl.",
          science: "Facing away from the cable machine creates continuous tension through the entire stretch.",
          timerSec: 75,
          trackWeight: true,
        },
      ],
    },
    {
      day: 6,
      title: "Legs & Abs",
      label: "Day 6 – Legs & Abs",
      note: "High-volume leg work and weighted ab training.",
      isOff: false,
      exercises: [
        {
          name: "Leg Press",
          sets: "3 x 10-12",
          cues: "Full depth without lower-back rounding, feet shoulder-width.",
          science: "Safe environment to take the leg muscles to absolute structural failure without lower back fatigue.",
          timerSec: 120,
          trackWeight: true,
        },
        {
          name: "Lying Leg Curls",
          sets: "3 x 10-12",
          cues: "Hips pinned to pad, curl heels to glutes, pause at contraction.",
          science: "Maximizes hamstring activation through knee flexion.",
          timerSec: 75,
          trackWeight: true,
        },
        {
          name: "Kneeling Cable Crunches",
          sets: "3 x 12-15",
          cues: "Hips fixed, crunch ribs to pelvis, exhale on contraction.",
          science: "Allows you to progressively add weight to abdominal training, making the six-pack pop.",
          timerSec: 60,
          trackWeight: true,
        },
      ],
    },
    {
      day: 7,
      title: "Strict Rest Day",
      label: "Day 7 – Strict Rest Day",
      note: "No Gym: Complete physiological rest. Muscle growth happens during rest, not during the workout.",
      isOff: true,
      exercises: [],
    },
  ];

  const GENERIC_GYM_SPLIT = [
    {
      key: "push",
      title: "Push — Chest, Shoulders & Triceps",
      note: "Compound pressing with triceps finishers.",
      isOff: false,
      exercises: [
        {
          name: "Barbell Bench Press",
          sets: "4 x 6-8",
          cues: "Scapula retracted, controlled eccentric.",
          timerSec: 120,
          trackWeight: true,
        },
        {
          name: "Incline Dumbbell Press",
          sets: "3 x 8-10",
          cues: "Drive elbows down and in, full range.",
          timerSec: 105,
          trackWeight: true,
        },
        {
          name: "Seated Dumbbell Shoulder Press",
          sets: "3 x 8-10",
          cues: "Brace core, no overarch.",
          timerSec: 105,
          trackWeight: true,
        },
        {
          name: "Cable Fly",
          sets: "3 x 12-15",
          cues: "Soft elbows, squeeze chest at center.",
          timerSec: 75,
          trackWeight: true,
        },
        {
          name: "Rope Triceps Pushdown",
          sets: "3 x 10-12",
          cues: "Elbows fixed, full extension.",
          timerSec: 75,
          trackWeight: true,
        },
      ],
    },
    {
      key: "pull",
      title: "Pull — Back & Biceps",
      note: "Row and pulldown focus with biceps work.",
      isOff: false,
      exercises: [
        {
          name: "Wide-Grip Lat Pulldown",
          sets: "4 x 8-10",
          cues: "Pull elbows to ribs, chest high.",
          timerSec: 105,
          trackWeight: true,
        },
        {
          name: "Seated Cable Row",
          sets: "4 x 8-10",
          cues: "Neutral spine, hold squeeze 1 sec.",
          timerSec: 105,
          trackWeight: true,
        },
        {
          name: "Face Pull",
          sets: "3 x 12-15",
          cues: "Elbows high, external rotation at finish.",
          timerSec: 75,
          trackWeight: true,
        },
        {
          name: "EZ-Bar Curl",
          sets: "3 x 8-10",
          cues: "No swinging, full elbow extension.",
          timerSec: 75,
          trackWeight: true,
        },
        {
          name: "Hammer Curl",
          sets: "3 x 10-12",
          cues: "Neutral grip, elbows fixed.",
          timerSec: 75,
          trackWeight: true,
        },
      ],
    },
    {
      key: "legs",
      title: "Legs & Core",
      note: "Lower-body compounds plus calf and core work.",
      isOff: false,
      exercises: [
        {
          name: "Leg Press",
          sets: "4 x 10",
          cues: "Full depth without lower-back rounding.",
          timerSec: 120,
          trackWeight: true,
        },
        {
          name: "Romanian Deadlift",
          sets: "4 x 8",
          cues: "Hip hinge and slow hamstring stretch.",
          timerSec: 120,
          trackWeight: true,
        },
        {
          name: "Leg Extension",
          sets: "3 x 12",
          cues: "Pause at contraction, control negative.",
          timerSec: 75,
          trackWeight: true,
        },
        {
          name: "Seated Leg Curl",
          sets: "3 x 12",
          cues: "Pause hard at contraction.",
          timerSec: 75,
          trackWeight: true,
        },
        {
          name: "Seated Calf Raise",
          sets: "4 x 12-15",
          cues: "Full stretch and full squeeze.",
          timerSec: 60,
          trackWeight: true,
        },
      ],
    },
  ];

  function resolveGif(name) {
    if (!name) return null;
    const lower = String(name).toLowerCase();
    const keys = Object.keys(EXERCISE_GIF_MAP).sort((a, b) => b.length - a.length);
    for (let i = 0; i < keys.length; i += 1) {
      if (lower.includes(keys[i])) return EXERCISE_GIF_MAP[keys[i]];
    }
    return null;
  }

  window.DADBOD_GYM = {
    EXERCISE_GIF_MAP,
    ADMIN_GYM_SPLIT,
    GENERIC_GYM_SPLIT,
    SCIENCE_RULES,
    resolveGif,
  };
})();
